from typing import Protocol

from src.orders.domain.order import Order, OrderStatus


class OrderRepositoryProtocol(Protocol):
    def add(self, order: Order) -> Order: ...
    def get(self, order_id: str) -> Order | None: ...
    def list_by_status(self, status: OrderStatus | None) -> list[Order]: ...
    def soft_delete(self, order_id: str) -> Order | None: ...
    def update_status(self, order_id: str, status: OrderStatus) -> Order | None: ...
