"""add deleted_at and indexes to orders

Revision ID: 73528209b9cd
Revises: cd168d2f5666
Create Date: 2026-05-11 15:35:12.079318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73528209b9cd'
down_revision: Union[str, Sequence[str], None] = 'cd168d2f5666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_column('orders', 'deleted_at')
    # ### end Alembic commands ###
